### ISSUE TITLE
Chord Chart & fixed content

### ISSUE THREAD

**Issue by Zanspins** [CircleSongs/CircleSongs#92]
We could have some fixed content pages such as chord charts (guitar, charango), info on songs or traditions, quechua vocab page, etc.
So to solve would be : 
how to add the pages (possible for user, or only by sending content to you as admin?)
how they are displayed and accessed from the home screen (database search page)

**Comment by dinshaw** [comment]
@Zanspins if you still want to do they, please make a list of pages you’d like. 
I have figured out how to do chord forms for guitar. I’ll open a separate ticket to track that work.

**Comment by dinshaw** [comment]
This all sounds good. Can you create the content for the static pages, noting any layout ideas you are having? How often will you want to edit? Then we can figure out the best way to add them to the app. 
For the Quechua, you want it laid out exactly like the song book has it? I'll probably add a table and you'll have to fill in the words, but then it will be very easy to maintain.

**Comment by dinshaw** [comment]
@Zanspins would you want the pages "Icaros" and "Quechua" to be visible to all users, or only if they enter the sacred password?

**Comment by Zanspins** [comment]
It's fine for all users to see the Icaros and Quechua page. 
Sorry to lag on creating the content you asked for. Lots of other Munay working happening right now. I'll get to these others when I get a chance, but have no clear estimate for when.
